# Generated by Django 4.2.1 on 2024-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('profile_img', models.ImageField(upload_to='user_image')),
            ],
        ),
    ]
